# .github/workflows/build.yml
name: Build and Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip app folder
      run: |
        zip -r app.zip ./app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-artifact           # <--- Important: matches deploy
        path: app.zip
